/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.androiddevchallenge.domain

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

class PetRepository {

    private val petsFlow = MutableStateFlow(
        NAMES.mapIndexed { index, name ->
            Pet(
                "$index",
                name,
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"
            )
        }
    )

    fun getPets(): StateFlow<List<Pet>> = petsFlow

    fun getPet(id: String): Pet? = petsFlow.value.find { it.id == id }

    companion object {
        private val NAMES = listOf(
            "Bella",
            "Charlie",
            "Luna",
            "Lucy",
            "Max",
            "Bailey",
            "Cooper",
            "Daisy",
            "Sadie",
            "Molly",
            "Buddy",
            "Lola",
            "Stella",
            "Tucker",
            "Bentley",
            "Zoey",
            "Harley",
            "Maggie",
            "Riley",
            "Bear",
            "Sophie",
            "Duke",
            "Jax",
            "Oliver",
            "Chloe",
            "Jack",
            "Penny",
            "Rocky",
            "Lily",
            "Milo",
            "Piper",
            "Toby",
            "Zeus",
            "Ellie",
            "Nala",
            "Roxy",
            "Winston",
            "Gracie",
            "Coco",
            "Murphy",
            "Dexter",
            "Teddy",
            "Ruby",
            "Diesel",
            "Rosie",
            "Marley",
            "Loki",
            "Scout",
            "Mia",
            "Leo",
            "Gus",
            "Abby",
            "Jake",
            "Finn",
            "Moose",
            "Ollie",
            "Koda",
            "Louie",
            "Hank",
            "Lilly",
            "Thor",
            "Pepper",
            "Gunner",
            "Willow",
            "Jackson",
            "Zoe",
            "Bandit",
            "Buster",
            "Blue",
            "Shadow",
            "Kona",
            "Baxter",
            "Dixie",
            "Henry",
            "Lexi",
            "Izzy",
            "Apollo",
            "Ginger",
            "Beau",
            "Layla",
            "Millie",
            "Gizmo",
            "Oscar",
            "Tank",
            "Bruno",
            "Jasper",
            "Lucky",
            "Dakota",
            "Ace",
            "Olive",
            "Brody",
            "Maverick",
            "Lulu",
            "Emma",
            "Oakley",
            "Sasha",
            "Belle",
            "Nova",
            "Athena",
            "Sammy",
            "Sam",
            "Copper",
            "Frankie",
            "Peanut",
            "Maya",
            "Winnie",
            "Remi",
            "Lady",
            "Boomer",
            "Bo",
            "Roxie",
            "Hazel",
            "Roscoe",
            "Annie",
            "Maddie",
            "Hunter",
            "Oreo",
            "Otis",
            "Ruger",
            "Rex",
            "Cali",
            "Ella",
            "Cash",
            "Cody",
            "Remy",
            "Callie",
            "Odin",
            "Chance",
            "Rocco",
            "Harper",
            "Tyson",
            "Ranger",
            "Luke",
            "Brutus",
            "Ziggy",
            "Bruce",
            "Honey",
            "Chewy",
            "George",
            "Wrigley",
            "Rusty",
            "Benny",
            "Phoebe",
            "Chase",
            "Princess",
            "Minnie",
            "Simba",
            "Brady",
            "Zeke",
            "Remington",
            "Paisley",
            "Shelby",
            "Holly",
            "Titan",
            "Leia",
            "Walter",
            "Samson",
            "Finley",
            "Ava",
            "Cookie",
            "Angel",
            "Mocha",
            "Archie",
            "Josie",
            "Rudy",
            "Benji",
            "Dozer",
            "Maximus",
            "Penelope",
            "Parker",
            "Joey",
            "Lincoln",
            "Romeo",
            "Ryder",
            "Kobe",
            "Aspen",
            "Mac",
            "Chief",
            "Missy",
            "Theo",
            "Chewie",
            "Axel",
            "Dallas",
            "Mila",
            "Bubba",
            "Xena",
            "Reese",
            "Chester",
            "Rufus",
            "Whiskey",
            "Macy",
            "King",
            "Watson",
            "Prince",
            "River",
            "Sunny",
            "Hudson",
            "Ivy",
            "Juno",
            "Kai"
        )
    }
}
